language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
     notifications:
    slack: theateam306:UShjsB7WVVqBiXKWpmzEgBn6
addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
   
