language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
   notifications:
  slack:
    rooms:
      - theateam306:HwfTqaMoXqouQiFj6DXp2nL4#general
      - theateam306:HwfTqaMoXqouQiFj6DXp2nL4#random
on_success: always
on_failure: always
